CREATE TABLE api_keys (
  id           BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id      VARCHAR(255) NOT NULL,
  provider     VARCHAR(64)  NOT NULL,
  encrypted_key VARBINARY(512) NOT NULL,
  version      INT NOT NULL DEFAULT 1,
  created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  UNIQUE KEY uniq_user_provider (user_id, provider)
);
