# Name of your application. Used to uniquely configure containers.
service: my-app

# Name of the container image.
image: my-user/my-app

# Deploy to these servers.
servers:
  web:
    - 192.168.0.1

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: example.com

# Credentials for your image host.
registry:
  server: ghcr.io
  username: my-user

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  secrets:
    - REPLICACHE_KEY

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
 clear:
   APP_APPLICATION__REDIS_URL: "redis://my-app-redis:6379"
   APP_APPLICATION__DATABASE_URL: "mysql://app:superpass@my-app-db:3306/myapp_production"
   APP_ENVIRONMENT: production
 secret:
   - APP_APPLICATION__SECRET
   - MYSQL_ROOT_PASSWORD


# Use accessory services (secrets come from .kamal/secrets).
accessories:
 db:
   image: mysql:8.0
   host: 192.168.0.1
   port: 192.168.0.1:3306:3306
   files:
      - config/mysql_native.cnf:/etc/mysql/conf.d/auth.cnf:ro
   env:
     clear:
       MYSQL_ROOT_HOST: '%'
       MYSQL_DATABASE: "myapp_production"
       MYSQL_USER: app
     secret:
       - MYSQL_ROOT_PASSWORD
       - MYSQL_PASSWORD
   directories:
     - data:/var/lib/mysql
 redis:
   image: valkey/valkey:8
   host: 192.168.0.1
   port: 192.168.0.1:6379:6379
   directories:
     - data:/data
